blog/urls.py
from django.urls import path
from .import views
#adding feed module
from .feeds import LatestPostsFeed

app_name='blog'

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),

]

mysite/urls.py
"""	We include these patterns under	the	namespace blog.Namespaces have to be unique	across your	entire project.Later,we will refer 
to	our	blog	URLs	easily	by	including the namespace,building them,for example,blog:post_list and blog:post_detail."""
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('blog/',include('blog.urls', namespace='blog1')),
    path('admin/', admin.site.urls),
	path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models

#1.importing user
from django.contrib.auth.models import User

#2.Importing time
from django.utils import timezone

#9.importing the url
from django.urls import reverse
#inserting the taggit manager
from taggit.managers import TaggableManager


#6.Writing the models
class PublishedManager(models.Manager): 
    def get_queryset(self): 
        return super(PublishedManager, self).get_queryset().filter(status='published')

#3Create your models here.
class Post(models.Model): 
    STATUS_CHOICES = ( 
        ('draft', 'Draft'), 
        ('published', 'Published'), 
    ) 
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250,  
                            unique_for_date='publish') 
    author = models.ForeignKey(User, 
                               on_delete=models.CASCADE,
                               related_name='blog_posts') 
    body = models.TextField() 
    publish = models.DateTimeField(default=timezone.now)
    #4.this filed get value automatic	value so it is not visible in the admin panel
    created = models.DateTimeField(auto_now_add=True) 
	#4.this filed get value automatic	value so it is not visible in the admin panel
    updated = models.DateTimeField(auto_now=True) 
    status = models.CharField(max_length=10,  
                              choices=STATUS_CHOICES, 
                              default='draft')
		
		
	#7creating the model manager for the objects						  
    objects = models.Manager() # The default manager.
	#8.Creating the object for the customised  model
    published = PublishedManager() # Our custom manager.
	
	#creating the object for taggable
    tags = TaggableManager()
							  
	#4.meta class for ordering in admin panel						  
    class Meta:
        ordering=('-publish',)
	#5.Writing the string represtation of object in admin panel	
    def __str__(self):
        return self.title
		
	#10.defining  get absolute urls
    '''The convention in Django is to add a get_absolute_url() method to the model that returns the canonical URL of	
	the	object.	For	this method,we will use the reverse() method that allows you to	build URLs by their	name and	
	passing	optional parameters'''	
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])
							 
class Comment(models.Model): 
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80) 
    email = models.EmailField() 
    body = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 
 
    class Meta: 
        ordering = ('created',) 
 
    def __str__(self): 
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

#making the forms for the email
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
	#here we do not make the email field required
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render,get_object_or_404
#1.Paginatior module
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
#2.Import Post
from .models import Post,Comment

#Importing List View
from django.views.generic import ListView

#Importing the email form from the form.py
from .forms import EmailPostForm,CommentForm

#importing gmail to send the msg
from django.core.mail import send_mail

#importing taggit application
from taggit.models import Tag



# Create your views here.
def post_list(request,tag_slug=None):
    object_list= Post.published.all()

    #we create the tag 
    tag=None

    #writing the if condition for tag

    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        object_list=object_list.filter(tags__in=[tag])
	
    '''We instantiate the Paginator class with the number of objects 
	we want to display on each page'''
    paginator = Paginator(object_list, 3) # 3 posts in each page
	
    """We get the page	GET	parameter that indicates the current
	page number."""
    page = request.GET.get('page')
	
    try:
	    #We obtain the objects for the desired page calling the page() method of Paginator.
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})
    
                 
def post_detail(request,year,month,day,post):
    posts = get_object_or_404(Post,slug=post,status='published'
						,publish__year=year,publish__month=month,
							 publish__day=day)
    
    comments=posts.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment =comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = posts
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    # List of similar posts
    post_tags_ids = posts.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                 .exclude(id=posts.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                .order_by('-same_tags','-publish')[:4]


    return render(request,'blog/post/detail.html',{'posts': posts,'comments':comments,'new_comment':new_comment,
                                    'comment_form':comment_form,'similar_posts':similar_posts})
				  
		

		
				  
class PostListView(ListView):
    #Use a specific QuerySet instead of retrieving	all	objects.Instead	of defining	a queryset attribute,we	could have specified model=Post and Django would have built the generic Post.objects.all() QuerySet for us.
    queryset = Post.published.all()
	#Use the context variable posts	for	the	query results.The default variable is object_list if we	don't specify any context_object_name.
    context_object_name = 'posts'
	#Paginate the result displaying	three objects per age.
    paginate_by = 3
	#Use a custom template to render the page.If we don't set a default	template,ListView will use blog/post_list.html.
    template_name = 'blog/post/list.html'
	
"""In order to keep pagination working,we have to use the right page object that is passed
	tothe	template.	Django's	ListView	generic	view passes	the	selected	page	in	a	
	variable	called	page_obj,	so	you	have	to edit	your	post/list.html	template	
	accordingly	to	include	the	paginator using	the	right	variable,	as	follows:
	{%	include	"pagination.html"	with	page=page_obj	%}"""

#post share by email function
def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post,id=post_id, status='published')
    sent = False 
 
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            #Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                                          post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com',
 [cd['to']])
            sent = True
    else:
	    #When the view is loaded initially with	a GET request,we create	a	
		#new form instance that	will be	used to	display	the empty form in the template
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
	                                               'form':form,
												   'sent':sent})
           

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %} 
 {% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %} 
 
{% block content %} 
  <h1>{{ posts.title }}</h1> 
  <p class="date"> 
    Published {{ posts.publish }} by {{ posts.author }} 
  </p> 
  {{ posts.body|markdown}} 
  <!--1 part for the share link-->
   <p>
   <a href='{% url "blog:post_share" posts.id %}'>
      Share this post
    </a>
    </p>
	
  <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    There are no similar posts yet.
  {% endfor %}

  {% with comments.count as total_comments %}
    <h2>
      <b>{{ total_comments }} comment{{ total_comments|pluralize }}</b>
    </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}

  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
    <h2>Add a new comment</h2>
    <form action="." method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Add comment"></p>
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
 {% load blog_tags %}
{% block title %}My Blog{% endblock %}
 
{% block content %}
  <h1>Krishna Story</h1>
  
  <!--writing the tag conditions-->
    {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h3>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
        <!--p class ="tags">Tags:{{ post.tags.all|join:","}}-->
      </a>
    </h3>
 <!----WRITING THE TAG SECOND CONDITIONS-->	
	<p class="tags">
      Tags:
      {% for tag in post.tags.all %}
        <a href='{% url "blog:post_list_by_tag" tag.slug %}'>
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    <!--{{ post.body|truncatewords:30|linebreaks }}-->
	{{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  <!-- in page pass posts but if we use list view then pass-->
  <!--In	order	to	keep	pagination	working,	we	have	to	use	the	right	page
object	that	is	passed	to	the	template.	Django's	ListView	generic	view passes	the	selected	page	in	a	variable	called	page_obj,	so	you	have	to edit	your	post/list.html	template	
accordingly	to	include	the	paginator using	the	right	variable,	as	follows:-->

  {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}